### ISSUE TITLE
mosdepth

### ISSUE THREAD

**Issue by Bohdan-Khomtchouk** [endrebak/chipcheck#2]
Can't we leverage this code ourselves?: 

https://academic.oup.com/bioinformatics/article/34/5/867/4583630?guestAccessKey=35b55064-4566-4ab3-a769-32916fa1c6e6

Seems quite relevant, especially for Python development...

**Comment by endrebak** [comment]
For nucleotide level calculations it seems useful. 

However, I have started reducing each read to its estimated midpoint as this is much faster and means that the chipcheck statistics are comparable across libraries with different readlengths.

**Comment by endrebak** [comment]
(It is actually written in nim, a language that looks like Python, but is compiled. Seems much nicer than the new golang to me and competes in the same space.)
